### PR TITLE
Fix blackscreen on iOS13

### PR DESCRIPTION
**Pull request by achernoprudov**
Fix from stackoverflow breaks tests on iOS13.

### CODE REVIEW

**Comment by achernoprudov** [comment]
Hi @kirian. Yes, it is.

**Comment by gilserrap** [comment]
Hi @achernoprudov ! Thanks a lot for this contribution, I've tested it and looks like it does the trick.

However, I've been! Thanks a lot for this contribution, I've tested it and looks like it does the trick, but I've been trying to remove the extension altogether and, on iOS 11 & up it works, so, I assume it's not necessary anymore.

Could you try to remove the extension and tell me if you get good results from it? I am still deciding what is the right solution.

**Comment by achernoprudov** [comment]
I removed extension but few tests fail on iOS13. It is EarlGrey bug and I don't think we are able to fix it in `Sencha` library.

**Comment by achernoprudov** [comment]
Also I tested fix with my project and all 146 ui tests are green.

**Comment by gilserrap** [comment]
@achernoprudov Yep, you're right, I've tried rebasing this branch onto your update of the EarlGrey version to 1.15, to see if that fixed anything, same results. I've tried several fixes with/without extension, attempting to present modal views in full screen to emulate prev ios versions, nothing. I think we are dependant on the good will of the EarlGrey devs.

I'm merging this PR since currently it's the best solution 👌

Maybe I'll migrate Sencha to EarlGrey 2.0 if I find some time.

**Comment by bellebethcooper** [comment]
@achernoprudov Thanks for fixing this! I had a go myself and couldn't figure it out. I updated to Sencha 0.13 and tried running my tests but I keep running into an error that says "Failed to execute block because idling resources below are busy." I think this is probably out of scope of Sencha, as it seems to be a direct issue with EarlGrey, but I wondered if you'd run into this yourself or have any ideas about how I might be able to fix it? It'd be so nice to get all my old tests running again and not have to rewrite them! Thanks again for your efforts on updating Sencha :)

**Comment by achernoprudov** [comment]
@bellebethcooper I tried to find problem inside EarlGrey yesterday. So I cloned EarlGrey repository and figured out that it has two tests targets. One for obj-c and one for swift. 

Objc target tests were ok even on iOS 13. But Swift tests failed with same idling resources error. 
I tried to go deeper and found problem with objc swizzling that check `viewWillAppear` calling. I have no idea why it fails only in Swift and will try to research it on weekends if I have spare time.

**Comment by bellebethcooper** [comment]
@achernoprudov Hey, thanks so much for the quick reply! I saw some issues from previous years with the same problem, where the EarlGrey team said it was fixed in newer versions (1.11 and 1.13), so I guess it might be something that breaks often with new iOS versions. It sounds like it's a pretty deep issue in EarlGrey—thanks for the extra info! I'm also trying to set up EarlGrey 2.0 but haven't found a way to do the same kind of white-box testing I did with EarlGrey 1.x so it seems like there's not a great option right now!

Really appreciate your help understanding this issue, thanks 👍

**Comment by gilserrap** [comment]
@achernoprudov @bellebethcooper I created an issue https://github.com/AdevintaSpain/Sencha/issues/22 so that we have somewhere to report any updates on the subject. 
Huge thanks to both!

**Pull request merged**
