### PR TITLE
Swift 5

### PR DESCRIPTION
**Pull request by achernoprudov**
Library migrated to Swift5.

### CODE REVIEW

**Comment by achernoprudov** [comment]
Also I updated EarlGrey version.

**Comment by bellebethcooper** [comment]
@achernoprudov Have you tested EarlGrey 1.15 with Xcode 11/iOS 13? I'm not clear on whether support for iOS 13 was added before EarlGrey switched to 2.0

**Comment by gilserrap** [comment]
@bellebethcooper https://github.com/google/EarlGrey/issues/1015#issuecomment-522061737 😢

**Comment by gilserrap** [comment]
@achernoprudov Awesome!

**Comment by bellebethcooper** [comment]
@gilserrap Ah, thanks. I was confused by [this comment](https://github.com/google/EarlGrey/issues/1015#issuecomment-532781368) and thought 1.15 might have been compatible. Too bad!

**Pull request merged**
